name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    # NOTE: Default option does not include `-o pipefail` as documented
    # unless explicitly specifying the `bash` shell.
    # https://github.com/actions/runner/issues/353
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 3

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.12.1"

      - name: Install PlatformIO
        run: |
          pip install --upgrade platformio
          pio --version

      - name: Run linter checks
        run: |
          pio check --skip-packages

  fmt:
    runs-on: ubuntu-22.04
    timeout-minutes: 3

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Install clang-format
        run: |
          sudo apt-get install -y clang-format
          clang-format --version

      - name: Run formatting checks
        run: |
          find ./src/ -iregex '.*\.\(c\|h\|cpp\|hpp\)$' -type f -print0 | xargs -0 -L1 clang-format -style=file --dry-run --Werror

  test-erc:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    container:
      image: kicad/kicad:9.0.4
      options: --user=root

    steps:
      # NOTE: Requires running KiCad container image as root
      # https://github.com/actions/checkout/issues/956
      - name: Checkout branch
        uses: actions/checkout@v5.0.0
        with:
          submodules: 'true'

      # NOTE: KiCad CLI expects the global tables to be in `~/.config/kicad/X.Y`
      # and this is already correctly set up in the KiCad Docker image but GitHub
      # Actions runs the container with a different `HOME` directory so we need
      # to copy these files over.
      - name: Set up global symbol/footprint tables
        run: |
          mkdir -p "${HOME}/.config"
          cp -Rv '/home/kicad/.config/kicad' "${HOME}/.config"

      - name: Ensure build directories exists
        run: |
          mkdir -p ./build/

      - name: Show KiCad version
        run: |
          kicad-cli version

      - name: Run tests
        run: |
          kicad-cli sch erc \
            --exit-code-violations \
            --output ./build/MitsubishiSC.rpt \
            ./hardware/MitsubishiSC.kicad_sch

      - name: Display report
        if: success() || failure()
        run: |
          cat ./build/MitsubishiSC.rpt

      - name: Upload report
        if: success() || failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: hw-rpt-erc
          path: ./build/

  test-drc:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    container:
      image: kicad/kicad:9.0.4
      options: --user=root

    steps:
      # NOTE: Requires running KiCad container image as root
      # https://github.com/actions/checkout/issues/956
      - name: Checkout branch
        uses: actions/checkout@v5.0.0
        with:
          submodules: 'true'

      # NOTE: KiCad CLI expects the global tables to be in `~/.config/kicad/X.Y`
      # and this is already correctly set up in the KiCad Docker image but GitHub
      # Actions runs the container with a different `HOME` directory so we need
      # to copy these files over.
      - name: Set up global symbol/footprint tables
        run: |
          mkdir -p "${HOME}/.config"
          cp -Rv '/home/kicad/.config/kicad' "${HOME}/.config"

      - name: Ensure build directories exists
        run: |
          mkdir -p ./build/

      - name: Show KiCad version
        run: |
          kicad-cli version

      - name: Run tests
        run: |
          kicad-cli pcb drc \
            --exit-code-violations \
            --schematic-parity \
            --output ./build/MitsubishiSC.rpt \
            ./hardware/MitsubishiSC.kicad_pcb

      - name: Display report
        if: success() || failure()
        run: |
          cat ./build/MitsubishiSC.rpt

      - name: Upload report
        if: success() || failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: hw-rpt-drc
          path: ./build/MitsubishiSC.rpt

  build-fw:
    needs:
      - lint
      - fmt
    runs-on: ubuntu-24.04
    timeout-minutes: 3

    steps:
      - name: Checkout branch
        uses: actions/checkout@v5.0.0

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.12.1"

      - name: Install PlatformIO
        run: |
          pip install --upgrade platformio
          pio --version

      - name: Compile firmware
        run: |
          pio run

  build-hw:
    needs:
      - test-erc
      - test-drc
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    container:
      image: kicad/kicad:9.0.4
      options: --user=root

    steps:
      # NOTE: Requires running KiCad container image as root
      # https://github.com/actions/checkout/issues/956
      - name: Checkout branch
        uses: actions/checkout@v5.0.0
        with:
          submodules: 'true'

      # NOTE: KiCad CLI expects the global tables to be in `~/.config/kicad/X.Y`
      # and this is already correctly set up in the KiCad Docker image but GitHub
      # Actions runs the container with a different `HOME` directory so we need
      # to copy these files over.
      - name: Set up global symbol/footprint tables
        run: |
          mkdir -p "${HOME}/.config"
          cp -Rv '/home/kicad/.config/kicad' "${HOME}/.config"

      # NOTE: The workspace directory is not marked as safe directory
      # when running in container due to Git config issues, so this
      # needs to be done explicitly.
      # https://github.com/actions/checkout/issues/1169
      # NOTE: The `GITHUB_WORKSPACE` variable must be used when running
      # in container because `github.workspace` refers to a different path.
      # https://github.com/actions/runner/issues/2058
      - name: Mark Git workspace as safe directory
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Show KiCad version
        run: |
          kicad-cli version

      # NOTE: Requires running KiCad container image as `runner` user
      # https://github.com/actions/runner/issues/2033
      - name: Generate export files
        run: |
          ./scripts/export.sh

      - name: Upload manufacturing artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: hw-build-mfg
          path: ./build/manufacturing/

      - name: Upload assembly artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: hw-build-asb
          path: ./build/assembly/

      - name: Upload schematic artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: hw-build-sch
          path: ./build/schematic/
